// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obiwgkerjwnpnivfvozf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iaXdna2VyanducG5pdmZ2b3pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NzI4MTUsImV4cCI6MjA2MDU0ODgxNX0.SAeLMxhZgWRDKCOqc4sv8UvhPChUQlfczL_noqRPsWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);